### PR TITLE
Fixed Navbar(2)

### PR DESCRIPTION
**Pull request by SameerJS6**
I made the same changes as before, but this time I re-cloned the repository. I'm hoping that there won't be any bugs after merging with the main branch.

Thank You,
SameerJS6

### CODE REVIEW

**Comment by sarmadhamdani02** [comment]
@SameerJS6 

Here is the same problem again. 🫤
image

When I test this locally it works fine but when I merge it, it causes the problem. It means there is something in the main code that when merged with this code causes the problem. That is what I think. 🤔

**Comment by sarmadhamdani02** [comment]
@SameerJS6

**Comment by SameerJS6** [comment]
Is there any way I could get the merged code? Like download it and then test it once?

**Comment by sarmadhamdani02** [comment]
@SameerJS6 

Well, you can clone the repository from https://github.com/sarmadhamdani02/WebGames.

**Pull request merged**
