### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by avinashji1302**
Improve the size of score button for smaller size in devquiz

please check

### CODE REVIEW

**Comment by sarmadhamdani02** [comment]
Hi, @avinashji1302, thanks for the great work 👏

The Score is looking perfect now.

But I have no idea why this problem is back again 😶, take a look at the screenshot below.

WhatsApp Image 2023-09-06 at 22 44 23

The problem is again the responsiveness issue in the main game panel ( where the question and all the options are present ). Can you please take a look at that?

**Comment by avinashji1302** [comment]
I will fix it tomorrow

**Comment by sarmadhamdani02** [comment]
> I will fix it tomorrow

Thank you, @avinashji1302! 🙏 For now, I'm going to merge this code.

**Comment by avinashji1302** [comment]
> > I will fix it tomorrow
> 
> Thank you, @avinashji1302! 🙏 For now, I'm going to merge this code.

Nahi karna chahiye tha bhaiya, main kal fix kar deta ise


It's okk, i will fix it tomorrow anyway 😍

**Pull request merged**
