### PR TITLE
Updated the styles for the tic-tac-toe game to include ten images

### PR DESCRIPTION
**Pull request by Cidmodder**
I added a folder called backgrounds and put all 10 images for the themes there.

On the JavaScript I changed the randomColor() function to randomTheme() for clarity. Currently it uses the random number to pick a url at random from the backgrounds and apply it to .main. I also updated all the calls for randomColor to randomTheme.

This does remove any link to the background color of the tic-tac-toe container at the end of the JavaScript file, , since all the if statements are now false. It should be easy to change around if you want other colors for the container.

In the CSS file, I updated the .main to stretch all of the images so there is no tiling effect.

### CODE REVIEW

**Comment by sarmadhamdani02** [comment]
We can also do something like,  after each level, the game-panel screen color also keeps changing.

What do you say?

**Comment by Cidmodder** [comment]
@sarmadhamdani02 

I like the idea of both of those. I'll work on that.

Sorry for the newbie question but this is my first pull request. I would make the commits to my fork still and it will update the pull request, correct? I don't need to make another pull request after I make those changes?

**Comment by sarmadhamdani02** [comment]
@Cidmodder 

Exactly just commit to your Forked repo.
And don't be shy to ask such questions, we all start at some point. 😊

**Comment by Cidmodder** [comment]
I updated the game container to be transparent and to have colors that match each background image.

**Comment by sarmadhamdani02** [comment]
I just reviewed the PR and what a great work you have done. It is really awesome, Well Done @Cidmodder. 👏👏
It is looking wonderful now,

image

However, I am a little bit concerned about one issue 🤔. Sometimes, the image takes time to load depending upon the internet speed and it looks something like below,

image

But, I think for now It is great. We can deal with this problem in the future. 🙂

**Pull request merged**
