### PR TITLE
Fixed the Navbar

### PR DESCRIPTION
**Pull request by SameerJS6**
### What does it do?

1. Completely Restyles the navbar 
2. Makes it responsive and more interactive while maintaining the original essence.
3. Utilizes Modern Web Development Practices
4. Increase Code Readability

### Why is it needed?

It helps others to better understand the basics of web development and improves the overall UI.

Before: 
Screenshot (105)

After: 
Screenshot (106)

Thank You,
SameerJs6.

### CODE REVIEW

**Comment by sarmadhamdani02** [comment]
I really loved the new buttons and their hover effect, also the sidebar is so good👏
But, Don't you think the height of the navbar is too much? 🤔

**Comment by SameerJS6** [comment]
> I really loved the new buttons and their hover effect, also the sidebar is so good👏

Thank you.❤️

> But, Don't you think the height of the navbar is too much? 🤔

Thank you for pointing that out. I'll definitely take a closer look and work on fixing it.

**Comment by SameerJS6** [comment]
### Implemented Changes
1. Decreased the Navbar's overall `padding-block` from `1.25rem` to `1rem`.
2. Readjusted the size of all Navigation Buttons. (Adjusted the font size and padding for the buttons)


### Before: 
Screenshot (106)

### After: 
Screenshot (107)

## Note 
- Furthermore, making adjustments could potentially lead to the navbar appearing cramped, which may not provide the best user experience.


What do you Say? @sarmadhamdani02 Now??

**Comment by sarmadhamdani02** [comment]
@SameerJS6 

Looking great.👏
Update the code through PR 🚀

**Comment by sarmadhamdani02** [comment]
@SameerJS6 , how about increasing the font size of the logo a bit? 🤔

**Comment by SameerJS6** [comment]
@sarmadhamdani02  Ok, but the current font size is 1rem, and if I increase font size any more than that, then it will increase the size of the navbar as in the height of the navbar.

So, do you still want it? or not?
Also, I feel like it is fine!

**Comment by sarmadhamdani02** [comment]
How about using `vw` instead of `rem` ? This is not bad though. If you think it is fine, leave it as it is.

**Comment by SameerJS6** [comment]
@sarmadhamdani02 

> How about using `vw` instead of `rem`?

Here, Do watch this video to get a better understanding of why we should not prefer viewport units over other units in projects. 
- [The problems with viewport units](https://youtu.be/veEqYQlfNx8)

>  This is not bad though. If you think it is fine, leave it as it is.

So, should I create a new pull request, now? or not?

**Comment by sarmadhamdani02** [comment]
@SameerJS6 

I think making the font size of only the logo text `1.6rem` can be a good idea. 🤔

Secondly, this branch is having conflicts. Some changes have been done in the main code so try entering `git pull` on the terminal.

**Comment by sarmadhamdani02** [comment]
Thanks for the video link though 🙂

**Comment by sarmadhamdani02** [comment]
As multiple changes have been made in the main code. You should enter the command git pull in your terminal. So that the recent changes can also be made in your code. 🤔

**Comment by SameerJS6** [comment]
Fixed the Conflict Issue

**Comment by sarmadhamdani02** [comment]
@SameerJS6 

The work you uploaded was working fine when checked locally.
But after merging that to the code this was the result 🤷‍♂️

image

so, I had no other choice than to revert the changes.

Not sure what is the problem here. 🫤

**Comment by SameerJS6** [comment]
Fine Then, I'll try to clone the repo again and then try again!!

**Pull request merged**
