### PR TITLE
Bug fixes regarding game restart for the Dev Quiz game

### PR DESCRIPTION
**Pull request by treblig-punisher**
-Fixed an infinite loop caused by a recursion bug where the questions asked array didn't get emptied.

- Fixed a bug where questions could be clicked multiple times causing the next question to get skipped.

-Fixed a bug where the theme wouldn't get changed upon restarting the game after the game over screen.

-changed all comparisons using == to using === for true check rather than type coercion.

### CODE REVIEW

**Comment by treblig-punisher** [comment]
Hey Sarmad, I have submitted my fixes to the game. The game was getting soft locked because of an infinite loop, and also it wasn't changing themes on restart either. It was also allowing for multiple clicks on the same answers causing big issues. All of this is now resolved.

**Comment by sarmadhamdani02** [comment]
Excellent Job @treblig-punisher  👏

It was a lot of work, wasn't it? 😄
Just remove those Console.log(); messages, and once that's done, I'll be able to merge the pull request.

image

**Comment by treblig-punisher** [comment]
> Excellent Job @treblig-punisher 👏
> 
> It was a lot of work, wasn't it? 😄 Just remove those Console.log(); messages, and once that's done, I'll be able to merge the pull request.
> 
> image

yeah, it was. I had to first find out how the game would know when it was over and what it was keeping track of. It looks like the changesI made didn't make it as I removed those logs. I'll get to it. Glad to be of help. I'll take a look at what other issues I can tackle as this was fun to fix.

**Comment by treblig-punisher** [comment]
Alright, all console.log lines should be completely removed now. Let me know

**Comment by sarmadhamdani02** [comment]
👏

**Pull request merged**
