### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by avinashji1302**
Please check fix the resposnsiveness of Dev Quiz

//Request 

Please provide the clear instruction of Installation

### CODE REVIEW

**Comment by avinashji1302** [comment]
> Please check fix the resposnsiveness of Dev Quiz

**Comment by avinashji1302** [comment]
> Hi thanks for the PR.
> 
> There is still same problem as shown in the screenshot below,
> 
> 
> 
> Also, the branch is having conflicts. Try `git pull` in the terminal in you directory which will import all the latest changes. Hopefully, this will solve the problems.

Please provide the clear instructions to install in our local system

I was doing directly by inspecting it that's why it's happening

**Comment by sarmadhamdani02** [comment]
Hi @avinashji1302 👋
Apologies for the slight delay in my response. I was a little busy with something.

I'm not sure how familiar you are with this topic, so I'll start from the very basics to make sure you can understand everything. Feel free to ask any questions you might have along the way.👍

### How to Setup?

- So, first of all, you have to go to the [master](https://github.com/sarmadhamdani02/WebGames/tree/master) branch. From there, you have to click on the code button, copy the HTTPS, and enter the `git clone {Copied HTTPS}` on the terminal. If you cannot understand what I am talking about, just go to the target folder (where you want to work), open the terminal on it, and enter the following command: `git clone https://github.com/sarmadhamdani02/WebGames.git`, this will clone the repository on your local folder.
- After that, open the VS Code (or whatever code editor you are using) in that folder. In the code editor, you will find a folder of "DevQuiz" where code related to the "Dev Quiz" game is present.
- Now, once that is done, open the `index.html` and run that in the live server (now, if you don't have any idea what a live server is, you can visit [this](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) website or just search about that on youtube, I am sure you will find something good). Live Server will open your website on your local browser so you will be able to see what changes you are making.

That was all how to start working. I hope I was able to explain. 🙂

### What to do?

Now, let's quickly let's talk about what problem you are going to solve.
So, the problem was we were having a responsiveness issue on the website. A user on mobile was not able to play because some options were getting outside the `div` and as, in that div, there was `overflow: hidden;`, so, the user was not even able to see that. Look at the screenshot attached to the issue you will get it.
So, in order to make the game playable on mobile as well we have to do something which will make all kinds of options visible. So how will we get that? Simple, either make that div (where options and questions are) scrollable, so the user will simply scroll it, or make a div a bit bigger. 🙌
The **Score** text is also so small on the mobile screen, so fix that as well if you could.

So, @avinashji1302 I tried my best to explain all the things to you and I hope I was able to make you understand. 🙂
If, you still have any questions related to this, please don't hesitate to ask.

Regards.

**Comment by avinashji1302** [comment]
okk Thanks , I am closing this and creating a new PR Please check!

**Pull request closed without merging**
