### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by avinashji1302**
"fix the responsiveness of Devquiz , Please check"

### CODE REVIEW

**Comment by sarmadhamdani02** [comment]
Great work @avinashji1302 👏
Now, the options are fully visible and user can play the game. 

But, I think there is still room for improvement 🤔. See, we don't only want to make game playable but also want to make it visually appealing.

As you can see in the screenshot below, the question and the options are more on the top of the screen, these will look much better in almost the middle of the screen. Also, reducing the height of the div on which the question and options are, will not be a bad decision.

One idea coming to my mind is to make the options scrollable. So, if options contains too many words due to which it will be hidden, user will just scroll down to see all options. 🤔

The score is so small, try to increase its side and make it visible for player.



Lastly, the end screen is looking a bit weird. I think making the **function gameResult()** size smaller solve the issue.

**Comment by avinashji1302** [comment]
> Great work @avinashji1302 👏 Now, the options are fully visible and user can play the game.
> 
> But, I think there is still room for improvement 🤔. See, we don't only want to make game playable but also want to make it visually more appealing.
> 
> As you can see in the screenshot below, the question and the options are more on the top of the screen, these will look much better in almost the middle of the screen. Also, reducing the height of the div on which the question and options are, will not be a bad decision.
> 
> One idea coming to my mind is to make the options scrollable. So, if options contains too many words due to which it will be hidden, user will just scroll down to see all options. 🤔
> 
> The score is so small, try to increase its side and make it visible for player.
> 
> 
> 
> Lastly, the end screen is looking a bit weird. I think making the **function gameResult()** size smaller solve the issue.
> 
> 




Please check Now

**Comment by sarmadhamdani02** [comment]
Great Work @avinashji1302 👏👏

**Comment by avinashji1302** [comment]
> Great Work @avinashji1302 👏👏

Thank You ...

if there is any other work   Please let me know

**Comment by sarmadhamdani02** [comment]
Hi @avinashji1302 

You did a great job and I just merged the pull request 👏

But, there is still an issue not solved yet and that is the Score font size issue. So, in mobile score font is so small that it is not visible. 

According to me, the best possible thing you can do for that is to add font size in the **media queries** for the **score**.

**Comment by avinashji1302** [comment]
> Hi @avinashji1302
> 
> You did a great job and I just merged the pull request 👏
> 
> But, there is still an issue not solved yet and that is the Score font size issue. So, in mobile score font is so small that it is not visible.
> 
> According to me, the best possible thing you can do for that is to add font size in the **media queries** for the **score**.

I will fix it tomorrow , Thank you

**Comment by sarmadhamdani02** [comment]
Sure no problem.

**Pull request merged**
