### PR TITLE
Fix #5 Added attractive thumbnails

### LINKED ISSUE #5: add some attractive thumbnails to the game
The games (Tic-Tac-Toe and The Bubble Game) have some thumbnails which are just some screenshots of the game. The thumbnails are not quite attractive. Add some attractive thumbnails.

### PR DESCRIPTION
**Pull request by AsharMallick**
Fixed issue #5

### CODE REVIEW

**Comment by sarmadhamdani02** [comment]
Thank you so much @AsharMallick  for the PR 🙌
However there are some problems I can see, look at the screenshot below, 

image

The tic-tac-toe one is working well but the bubble game one is not being visible for some reason.
I'm not sure if the issue lies in the image being too small or if I've made a mistake in my approach. Could you please review it and let me know if there's anything I'm doing incorrectly? 

By the way thanks for formatting the HTML code too 👏🙂

**Comment by sarmadhamdani02** [comment]
Ok, I am so sorry for the earlier comment. I think I was doing something wrong.
But now the thumbnail is being shown. Again, the "Tic-Tac-Toe" one is great 👏 but I think there are some changes required in the "The Bubble Game" one 🤔. Firstly, it looks a bit compressed, of course, it can be made better with the help of some CSS properties. But as the background is white and the image has no border it is not looking right. Kindly review it.

image

**Comment by sarmadhamdani02** [comment]
👏

**Comment by sarmadhamdani02** [comment]
Hey @AsharMallick 👋
I merged your code. The tic tac toe image was great 👏 but the other one was a bit low quality I think.
So I have added my own image. Screenshot given below,

Before: 
image

Now:
image

Tell me about what you think about this.

**Comment by AsharMallick** [comment]
It's great 👍

**Pull request merged**
