### PR TITLE
Added themes to the Tic Tac Toe game 

### PR DESCRIPTION
**Pull request by SandipGyawali**
#11 (Issue)
Added three different themes to the game and each time the theme gets restarted the random theme will be setup in the game.
@sarmadhamdani02

### CODE REVIEW

**Comment by sarmadhamdani02** [comment]
I really loved all the themes, really nice work 👏👏

However, I personally think the border colors of the `game-panel` (class in HTML) and the text were better in white color 🤔 I think it is much better to leave them as they were. What do you think?

Apart from this everything is fantastic.

**Comment by SandipGyawali** [comment]
ok i will change it

**Comment by SandipGyawali** [comment]
@sarmadhamdani02  can you review my pull requestion now ?

**Comment by sarmadhamdani02** [comment]
@SandipGyawali 

I fixed the borders of the `game-panel` which is great 👏 but I was also talking about the text (O/X) in it.


image

**Comment by SandipGyawali** [comment]
oh ok will fix that

**Comment by SandipGyawali** [comment]
@sarmadhamdani02 check the project again

**Comment by sarmadhamdani02** [comment]
@SandipGyawali 

Now, that is awesome 👏

**Comment by sarmadhamdani02** [comment]
Good point 💯 @SandipGyawali 

Although I have created the issue, let it be solved by some other beginner. Let's see other problems 💪

**Comment by SandipGyawali** [comment]
Ok. Tell me if you find any similar kind of issue a bit challenging. I will be happy to contribute to it. 
And if I find any other extra issues I will reach out to you so we can both solve the issue and progress simultaneously.

**Comment by sarmadhamdani02** [comment]
Sure! it will be great 👍

**Comment by SandipGyawali** [comment]
are there any issues that you are familiar with right now? If yes then let's contribute to it. I don't have any contribution to make right now.

**Comment by sarmadhamdani02** [comment]
> are there any issues that you are familiar with right now? If yes then let's contribute to it. I don't have any contribution to make right now.

@SandipGyawali Some issues have been added, you can check them out.

**Pull request merged**
