### PR TITLE
Website responsiveness issue

### PR DESCRIPTION
**Pull request by lefty93**
Solve for main website responsiveness issue #58. The result is as follows: (Please ignore the extra dev quiz):
image

### CODE REVIEW

**Comment by sarmadhamdani02** [comment]
Hi @lefty93 
Thank you so much for the work 🙏

But there is small problem 😕 , now, dark mode is not working as it should. You can see the screenshot below.

**Comment by lefty93** [comment]
Sorry, I didn't notice about this. I guess the issue is solved.
image

**Comment by sarmadhamdani02** [comment]
Hello, @lefty93! 👋
Thank you for your efforts. 🙂

However, there are still a few issues. I've observed that these problems are not only on mobile but also on desktop.

Desktop Issue:
image

Mobile Version Issue:
Additionally, the mobile version isn't functioning perfectly. Here's a screenshot showcasing the problem:

image

As you can see both websites are having problems from the bottom of the webpage.

**Comment by lefty93** [comment]
I guess this is due to the height in main-content. The previous one is set as "calc(100vh - 190px)". I have set it to 100vh.

**Comment by sarmadhamdani02** [comment]
Great Job @lefty93 👏

Thanks for pointing that out. The reason we had  `height: calc(100vh - 190px);` was because we also had a nav bar on the top and we had to minus the nav bar height from the `.main-content` in order to adjust its height on the main screen. But I just noticed that we were also having `overflow: hidden;` due to which we cannot have any problems in the near future or until we are having small number of games. 😄 

Regards.

**Pull request merged**
