### PR TITLE
Added buttons with 3D click effects #12

### PR DESCRIPTION
**Pull request by anubhav1206**
Added a 3D button on the following screens: 
image
image
image
image

### CODE REVIEW

**Comment by sarmadhamdani02** [comment]
Great work 👏

I think it will be better if you keep the previous fonts and buttons' background colors 🤔 can you do that?

**Comment by anubhav1206** [comment]
> Great work 👏
> 
> I think it will be better if you keep the previous fonts and buttons' background colors 🤔 can you do that?

I can definitely give it a shot. Do you want a blue color button for the bubble game and a yellow one for the tic tac toe game?

**Comment by sarmadhamdani02** [comment]
@anubhav1206 

Just keep the colors and font the same as the code has right now (https://sarmadhamdani02.github.io/WebGames/).

Also, I can see that the text is wrapped in the image below,
image

I think the button is looking good with the following `nowrap`ed font, font size, and button color, and hover effect as below.
image

What do you think?

**Comment by anubhav1206** [comment]
> 

So I'll revert the changes I have made?

**Comment by sarmadhamdani02** [comment]
@anubhav1206 

Keep the 3D effect it is cool 👏

I'm just saying keep the font color and button background color as they are.

**Comment by anubhav1206** [comment]
> @anubhav1206
> 
> Keep the 3D effect it is cool 👏
> 
> I'm just saying keep the font color and button background color as they are.

Got it, will update.

**Comment by anubhav1206** [comment]
> > @anubhav1206
> > Keep the 3D effect it is cool 👏
> > I'm just saying keep the font color and button background color as they are.
> 
> Got it, will update.

I have made the requested changes. Kindly check.

**Comment by sarmadhamdani02** [comment]
Nice work @anubhav1206 👏👏

As you can see that the button is too much below at the bottom. Make `margin-top`  from `60vh` to `margin-top: 55vh;` so that the button will be fully visible. Also add `over-flow: hidden` it will remove the scroll bars. 🤔

image

Also,  in  `.video-game-button` remove width, it will make the button adjust width automatically and the text will be in one line.

**Comment by sarmadhamdani02** [comment]
image

Also I am getting this high score error

**Comment by anubhav1206** [comment]
> image
> 
> Also, I am getting this high score error
> 
> Also, make play again button in one line as mentioned for the tic tac toe one button.

I have made changes on the button but can't figure out the high score error.

**Comment by sarmadhamdani02** [comment]
Thank you so much for the nice work @anubhav1206 👏👏 you did a great job.
Let me merge this.

**Pull request merged**
